alias: Offcourse
curator: Offcourse
description: I am an entrepreneur, thinker, and coder. Nowadays, I like to call myself an ecosystem architect. Concretely, this means that I bring people together around common values, discover a shared vision, and translate this into effective ecosystems.
socials:
  linkedin: "https://www.linkedin.com/in/yeehaa/"
  github: "https://www.github.com/yeehaa123/"
  instagram: "https://www.instagram.com/yeehaa12345/"
